# Generated by Django 2.2.2 on 2020-03-22 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=32)),
                ('Middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('Last_name', models.CharField(max_length=32)),
                ('Father_name', models.CharField(blank=True, max_length=32, null=True)),
                ('Mother_name', models.CharField(blank=True, max_length=32, null=True)),
                ('Married_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Not Married')], default='Not Married', max_length=100)),
                ('Spouse_name', models.CharField(blank=True, max_length=32, null=True)),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=100)),
                ('Phone1', models.CharField(max_length=10)),
                ('Phone2', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Current_address', models.CharField(max_length=200)),
                ('Current_address_pin', models.CharField(max_length=6)),
                ('Current_address_city', models.CharField(max_length=50)),
                ('Current_address_state', models.CharField(max_length=50)),
                ('Permanent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('Permanent_address_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('Permanent_address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('Permanent_address_state', models.CharField(blank=True, max_length=50, null=True)),
                ('Aadhaar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('PAN_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Voter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('Passport', models.CharField(blank=True, max_length=50, null=True)),
                ('Driver_license', models.CharField(blank=True, max_length=50, null=True)),
                ('Bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=50, null=True)),
                ('Job_title', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Work_place', models.CharField(max_length=50)),
                ('Work_location', models.CharField(max_length=50)),
                ('Date_of_joining', models.DateField()),
                ('Work_email', models.CharField(blank=True, max_length=50, null=True)),
                ('Official_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Reporting_officer', models.CharField(blank=True, max_length=50, null=True)),
                ('Emergency_contact_name', models.CharField(max_length=50)),
                ('Emergency_contact_relation', models.CharField(max_length=50)),
                ('Emergency_contact_phone1', models.CharField(max_length=10)),
                ('Emergency_contact_phone2', models.CharField(max_length=10)),
                ('Emergency_contact_email', models.CharField(max_length=50)),
                ('Emergency_contact_address', models.CharField(max_length=200)),
                ('Nominee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Nominee_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('Nominee_contact_phone1', models.CharField(blank=True, max_length=10, null=True)),
                ('Nominee_contact_phone2', models.CharField(blank=True, max_length=10, null=True)),
                ('Nominee_contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('Nominee_contact_address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(on_delete=models.SET('article desk'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
