# Generated by Django 2.2.2 on 2020-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200328_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customsettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Setting', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
