# Generated by Django 2.2.2 on 2020-04-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_customsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customsettings',
            new_name='Customsetting',
        ),
    ]
