# Generated by Django 2.2.2 on 2020-05-14 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200401_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='by',
            field=models.ForeignKey(on_delete=models.SET('Manually'), to=settings.AUTH_USER_MODEL),
        ),
    ]
