# Generated by Django 2.2.2 on 2020-05-14 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_code', models.CharField(default='', max_length=32, null=True)),
                ('Department', models.CharField(default='', max_length=32, null=True)),
                ('Ctc', models.IntegerField(default=0, help_text='Annual cost to company', max_length=32)),
                ('Location', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('Description', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Notes', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('user_firm', models.TextField(blank=True, default='', null=True)),
                ('by', models.ForeignKey(on_delete=models.SET('Manually'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
