# Generated by Django 2.2.2 on 2020-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Ctc',
            field=models.CharField(default=0, help_text='Annual cost to company', max_length=32),
        ),
    ]
