# Generated by Django 2.2.2 on 2020-05-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20200515_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Designation',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='Department',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
