# Generated by Django 2.2.2 on 2020-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20200515_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Job_code',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
