# Generated by Django 2.2.2 on 2020-05-24 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_auto_20200524_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='by',
            field=models.ForeignKey(on_delete=models.SET('USER IS REMOVED'), to=settings.AUTH_USER_MODEL),
        ),
    ]
