# Generated by Django 2.2.2 on 2020-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_auto_20200525_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
