# Generated by Django 2.2.2 on 2020-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_job_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_code',
            field=models.CharField(default='sfms', max_length=32),
        ),
    ]
