# Generated by Django 2.2.2 on 2020-05-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_auto_20200525_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_code',
        ),
    ]
