# Generated by Django 2.2.2 on 2020-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0011_remove_job_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_code',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='user_firm',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
