# Generated by Django 2.2.2 on 2020-06-08 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0015_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='by',
        ),
        migrations.AddField(
            model_name='candidate',
            name='By',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('USER IS REMOVED'), to=settings.AUTH_USER_MODEL),
        ),
    ]
